/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pushing_reduced_constr_h_fun_jac_uxt_zt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s5[15] = {13, 3, 0, 2, 4, 9, 11, 12, 11, 12, 0, 1, 4, 11, 12};
static const casadi_int casadi_s6[24] = {13, 13, 0, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 8, 11, 12, 11, 12, 0, 1, 0, 1};
static const casadi_int casadi_s7[6] = {0, 3, 0, 0, 0, 0};

/* pushing_reduced_constr_h_fun_jac_uxt_zt_hess:(i0[8],i1[5],i2[3],i3[],i4[10])->(o0[3],o1[13x3,9nz],o2[13x13,8nz],o3[0x3],o4[]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=arg[4] ? arg[4][3] : 0;
  a1=arg[0] ? arg[0][6] : 0;
  a2=(a0*a1);
  a3=arg[0] ? arg[0][7] : 0;
  a2=(a2-a3);
  if (res[0]!=0) res[0][0]=a2;
  a2=(a0*a1);
  a2=(a2+a3);
  if (res[0]!=0) res[0][1]=a2;
  a2=(a0*a1);
  a2=(a2-a3);
  a4=arg[1] ? arg[1][0] : 0;
  a5=(a2*a4);
  a1=(a0*a1);
  a1=(a1+a3);
  a3=arg[1] ? arg[1][1] : 0;
  a6=(a1*a3);
  a5=(a5+a6);
  a6=arg[1] ? arg[1][4] : 0;
  a5=(a5+a6);
  if (res[0]!=0) res[0][2]=a5;
  if (res[1]!=0) res[1][0]=a0;
  a5=-1.;
  if (res[1]!=0) res[1][1]=a5;
  if (res[1]!=0) res[1][2]=a0;
  a5=1.;
  if (res[1]!=0) res[1][3]=a5;
  if (res[1]!=0) res[1][4]=a2;
  if (res[1]!=0) res[1][5]=a1;
  if (res[1]!=0) res[1][6]=a5;
  a5=(a4*a0);
  a1=(a3*a0);
  a5=(a5+a1);
  if (res[1]!=0) res[1][7]=a5;
  a3=(a3-a4);
  if (res[1]!=0) res[1][8]=a3;
  a3=arg[2] ? arg[2][2] : 0;
  a4=(a0*a3);
  if (res[2]!=0) res[2][0]=a4;
  a4=(-a3);
  if (res[2]!=0) res[2][1]=a4;
  a4=(a0*a3);
  if (res[2]!=0) res[2][2]=a4;
  if (res[2]!=0) res[2][3]=a3;
  a4=(a3*a0);
  if (res[2]!=0) res[2][4]=a4;
  a0=(a3*a0);
  if (res[2]!=0) res[2][5]=a0;
  a0=(-a3);
  if (res[2]!=0) res[2][6]=a0;
  if (res[2]!=0) res[2][7]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int pushing_reduced_constr_h_fun_jac_uxt_zt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void pushing_reduced_constr_h_fun_jac_uxt_zt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void pushing_reduced_constr_h_fun_jac_uxt_zt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pushing_reduced_constr_h_fun_jac_uxt_zt_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int pushing_reduced_constr_h_fun_jac_uxt_zt_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT const char* pushing_reduced_constr_h_fun_jac_uxt_zt_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pushing_reduced_constr_h_fun_jac_uxt_zt_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pushing_reduced_constr_h_fun_jac_uxt_zt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pushing_reduced_constr_h_fun_jac_uxt_zt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pushing_reduced_constr_h_fun_jac_uxt_zt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
